services:
  - type: web
    name: uni-scraper
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 18
    autoDeploy: true
